apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "mem-chart.fullname" . }}-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
