apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mem-chart.fullname" . }}-client
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mem-chart.fullname" . }}-client
  template:
    metadata:
      labels:
        app: {{ include "mem-chart.fullname" . }}-client
    spec:
      containers:
      - name: mem-client
        image: abooumair/mem-client:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "mem-chart.fullname" . }}-client-config
              key: BACKEND_URL
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
