apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mem-chart.fullname" . }}-mongodb-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  mongo-db: {{ .Values.mongodbSecret }}
