apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "mem-chart.fullname" . }}-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000